const fakeProfiles = [
	{
		description: 'asdfasdf',
		familyStatus: 'married',
		kids: '0',
		wannaKidsMore: 'yes',
		languages: 'Italian',
		levelOfFaith: '',
		akida: 'Sufism',
		convertMuslim: 'no',
		originRace: 'white',
		appearance: {
			height: '180',
			weight: '90',
			disability: 'no',
		},
		origin: {
			nationality: 'Italian',
			countryOfBirth: 'Italia',
			countryLiveNow: 'France',
			cityLiveNow: 'Paris',
			statusResident: 'Resident',
		},
		career: {
			qualification: 'Driver',
			jobTitle: 'Driver',
			specialization: 'Cooker',
			education: 'middle',
		},
		incomeMonth: '3000',
		incomeYear: '45000',
	},
	{
		description: '122131',
		familyStatus: 'married',
		kids: '0',
		wannaKidsMore: 'yes',
		languages: 'Italian',
		levelOfFaith: '',
		akida: 'Sufism',
		convertMuslim: 'no',
		originRace: 'white',
		appearance: {
			height: '177',
			weight: '60',
			disability: 'no',
		},
		origin: {
			nationality: 'Italian',
			countryOfBirth: 'Italia',
			countryLiveNow: 'France',
			cityLiveNow: 'Paris',
			statusResident: 'Resident',
		},
		career: {
			qualification: 'Guid',
			jobTitle: 'Guid',
			specialization: 'Truism',
			education: 'Master',
		},
		incomeMonth: '4500',
		incomeYear: '65000',
	},
	{
		description: 'gsafd',
		familyStatus: 'divorced',
		kids: '1',
		wannaKidsMore: 'yes',
		languages: 'Germany',
		levelOfFaith: 'shia',
		akida: 'shia',
		convertMuslim: 'no',
		originRace: 'black',
		appearance: {
			height: '159',
			weight: '57',
			disability: 'no',
		},
		origin: {
			nationality: 'Iran',
			countryOfBirth: 'Iran',
			countryLiveNow: 'Germany',
			cityLiveNow: 'Berlin',
			statusResident: 'Resident',
		},
		career: {
			qualification: 'Driver',
			jobTitle: 'Driver',
			specialization: 'Cooker',
			education: 'middle',
		},
		incomeMonth: '5000',
		incomeYear: '75000',
	},
	{
		description: 'Hello',
		familyStatus: 'married',
		kids: '3',
		wannaKidsMore: 'yes',
		languages: 'Arabic',
		levelOfFaith: 'just muslim',
		akida: 'Ahlu sunna',
		convertMuslim: 'no',
		originRace: 'white',
		appearance: {
			height: '190',
			weight: '120',
			disability: 'no',
		},
		origin: {
			nationality: 'Arab',
			countryOfBirth: 'Saudi',
			countryLiveNow: 'Saudi',
			cityLiveNow: 'Mekka',
			statusResident: 'Resident',
		},
		career: {
			qualification: 'Finance',
			jobTitle: 'Finance analitic',
			specialization: 'Cooker',
			education: 'middle',
		},
		incomeMonth: '3000',
		incomeYear: '45000',
	},
	{
		description: 'asdfasdf',
		familyStatus: 'married',
		kids: '0',
		wannaKidsMore: 'yes',
		languages: 'Italiano',
		levelOfFaith: '',
		akida: 'Sufism',
		convertMuslim: 'no',
		originRace: 'white',
		appearance: {
			height: '180',
			weight: '90',
			disability: 'no',
		},
		origin: {
			nationality: 'Italian',
			countryOfBirth: 'Italia',
			countryLiveNow: 'France',
			cityLiveNow: 'Paris',
			statusResident: 'Resident',
		},
		career: {
			qualification: 'Driver',
			jobTitle: 'Driver',
			specialization: 'Cooker',
			education: 'middle',
		},
		incomeMonth: '3000',
		incomeYear: '45000',
	},
]
